#17/09/2025
### EJERCIOS DE PRACTICA ###

 #  EJERCICIO 1 CREAR Y MOSTRAR
# CREAR UNA LISTA CON 5 FRUTAS, MUESTRA EN PANTALLA LA LISTA COMPLETA, IMPRIME SOLO LA FRUTA QUE ESTE EN LA POSICION 2.
Frutas=["mango","pera","manzana","borojo","lulo"]
print(Frutas)
print(Frutas[1]),

    #EJERCICIO 2 MODIFICAR
## CREAR UNA LISTA CON LOS NUMEROS [5,10,15,20], CAMBIA EL NUMERO 15 POR 30, MUESTRA LA LISTA ACTUALIZADA
lista=[5,10,15,20]
lista.remove(15)
lista.insert(2,30)
print(lista)

    ##EJERCICIO 3 AGREGAR
## CREAR UNA LISTA CON 2 COLORES, USA APPEND() PARA AGREGAR UN COLOR AL FINAL
## USA INSERT() PARA PONER OTRO COLOR EN LA POSICION 0, IMPRIME LA LISTA COMPLETA

colores=["rojo","amarillo","azul"]
colores.append("blanco")
colores.insert(0,"negro")
print(colores)

    ## EJERCICIO 4 ELIMINAR
##CREA UNA LISTA CON ANIMALES:[PERRO,GATO,LORO,CONEJO], ELIMINA CONEJO USANDO REMOVE, ELIMINA EL ULTIMO ELEMENTO CON POP, MUESTRA LA LISTA

animales=["perro","gato","loro","conejo"]
animales.remove("conejo")
animales.pop()
print(animales)

    ## EJERCICIO 5 RECORRRER EL BUCLE
## CREA UNA LISTAS CON 4 NOMBRE DE PERSONAS
## RECORRE LA LISTA CON UN FOR E IMPRIME CADA NOMBRE EN PANTALLA
Nombres=["ana","luisa","camila","angelica"]
for nombre in Nombres:
    print(nombre)

    ## EJERCICIO 6: LISTA DE NUMEROS
#CREA UNA LISTAS CON LOS NUMEROS DEL 1 AL 5,CALCULA LA SUMA DE TODOS LOS NUMEROS DE LA LISTA(PUEDES USAR SUM)
#CALCULA LA CANTIDA DE ELEMENTOS CON LEN
#IMPRIME LOS RESULTADOS
Numeros=[1,2,3,4,5]
print(sum(Numeros))
print(len(Numeros))
